#ifndef BATTLESHIP_BATTLESHIP_INCLUDE_GRIGLIA_ATTACCO_H_
#define BATTLESHIP_BATTLESHIP_INCLUDE_GRIGLIA_ATTACCO_H_

#include "griglia.h"

class griglia_attacco {

};

#endif //BATTLESHIP_BATTLESHIP_INCLUDE_GRIGLIA_ATTACCO_H_
